In [77]:
import os
import json
import pandas as pd
import ast

### 1a. Parse the event annotations

In [78]:
# Define the folder path
folder_path = 'C:/Users/dawn/Desktop/SNA_try/Fujian_Bridge'

# Initialize an empty list to store data
data = []

record_counter = 1

# Iterate through the files in the folder
for file_name in os.listdir(folder_path):
    # Check if the file ends with 'txt_markus_event'
    if file_name.endswith('txt_markus_event.json'):
        # Construct the full file path
        file_path = os.path.join(folder_path, file_name)
        # Read the JSON data from the file
        with open(file_path, 'r', encoding='utf-8') as f:
            json_data = json.load(f)
        # Extract information from the JSON data
        for entry in json_data:
            record_id = f'record{record_counter:03d}'
            record_counter += 1
            # Get the original ID from the JSON
            original_id = entry['id']
            # Initialize a dictionary to store data for this entry
            entry_data = {'Record_ID': record_id,'Original_ID': original_id, 'File_Name': file_name}
            # Process "TIME" information
            time_info = entry.get('TIME', [])
            for time_data in time_info:
                time_type = time_data.get('type')
                time_text = time_data.get('text')
                time_id = time_data.get('id')
                entry_data[f'TIME_{time_type}_text'] = time_text
                entry_data[f'TIME_{time_type}_id'] = time_id
            # Process other keys
            for key, value in entry.items():
                if key != 'TIME':  # Skip 'TIME' as we already processed it
                    if isinstance(value, list) and all(isinstance(item, dict) for item in value):
                        # Concatenate all information from multiple entries into a single cell separated by ";"
                        entry_data[f'{key}_info'] = ";".join([str(item) for item in value])
                    else:
                        entry_data[key] = value
            # Append the entry data to the main data list
            data.append(entry_data)

# Convert the list of dictionaries to a DataFrame
df = pd.DataFrame(data)

### 1b. Check the information parsed

In [79]:
df

,Record_ID,Original_ID,File_Name,TIME_BEGIN_text,TIME_BEGIN_id,TIME_END_text,TIME_END_id,TIME_DURATION_text,TIME_DURATION_id,INITIATOR_info,...,OBJECT_WIDTH_info,OBJECT_HEIGHT_info,LABOR_info,TIME_None_text,TIME_None_id,PLACE_LINKED_info,TIME_BEFORE_text,TIME_BEFORE_id,TIME_AFTER_text,TIME_AFTER_id
0,record001,c67862cf-a766-4c45-89eb-ce4c3d71b8e1,Daoguang_ZhangpingXianzhi_Juanshou_Bubian_Wang...,九年三月,1829-04,復月望日,1829-05-17,不數月,x1月,{'markus_id': 'ccd1b930-e47b-498f-a2be-c6ae4f5...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,record002,722e1ac9-4a50-4532-9551-0f2ecef1bb76,Guangxu_PingnanXianzhi_Juanzhishi_Yiwen_HuangX...,NaN,NaN,甲辰,1904,不數月,x1月,{'markus_id': '5af1576b-dda1-46a6-9556-8963e54...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,record003,9eaccae1-9f20-46c7-8c82-48e835b21724,Guangxu_PingnanXianzhi_Juanzhishi_Yiwen_ZhouDa...,NaN,NaN,嘉慶十四年,1809,NaN,NaN,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,record004,c3d348c4-2be6-4f64-9380-99f437f9681f,Guangxu_PingnanXianzhi_Juanzhishi_Yiwen_ZhouDa...,NaN,NaN,嘉慶二十五年,1820,NaN,NaN,{'markus_id': '357475b9-d32d-49c4-8337-60dfe31...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,record005,e808dcda-4cdf-49e7-9487-9436ace47d56,Guangxu_PuchengXianzhi_Juanzhisanshiliu_Yiwens...,NaN,NaN,嘉靖六年,1527,NaN,NaN,{'markus_id': 'efbd2cf3-32a3-4631-bcf2-32dc2f5...,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426,record427,39ab932f-2ade-4538-9f02-7b2d69440858,Wanli_ZhengheXianzhi_Juanzhiba_Cihanzhi_YinZhi...,NaN,NaN,成化甲辰夏,1484,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
427,record428,ed918c3e-acce-472e-a4a5-d2313bf02a18,Wanli_ZhengheXianzhi_Juanzhiba_Cihanzhi_YinZhi...,明年秋,1485,NaN,NaN,半載,6月,{'markus_id': '2d3f9ca1-4b13-4f64-bdca-88a8cce...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
428,record429,507ce767-3298-454d-b348-729bf4a189de,Wanli_ZhengheXianzhi_Juanzhiba_Cihanzhi_ZouXix...,NaN,NaN,嘉靖乙卯,1555,NaN,NaN,{'markus_id': '72a3f009-8c83-437d-98ce-8529c45...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429,record430,c339a5f3-fc75-46dd-bfb9-481a85342d5b,Wanli_ZhengheXianzhi_Juanzhiba_Cihanzhi_ZouXix...,NaN,NaN,萬曆乙未,1595,NaN,NaN,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
430,record431,4137ccca-3d31-47ad-bed5-4da54cac67c6,Wanli_ZhengheXianzhi_Juanzhiba_Cihanzhi_ZouXix...,NaN,NaN,丁酉,1597,幾閱月,x1月,{'markus_id': 'a96f055a-4356-4eb8-91de-b5cf62e...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
print(df['INITIATOR_info'].iloc[1])

{'markus_id': '5af1576b-dda1-46a6-9556-8963e54ffce0', 'text': '住持', 'id': 'abbot'};{'markus_id': '0c3253a0-838f-4186-bfb4-ed8b13f159ae', 'text': '地慧', 'id': '地慧|fl1904|r屏南'}

In [6]:
print(df['SPONSOR_info'].iloc[1])

{'markus_id': '1efc67e1-07e7-422b-a715-f7ce3d8834bb', 'text': '有財者', 'id': 'wealthy'};{'markus_id': '2d4caee5-7a5a-4f2a-8420-aab4c2ce12c8', 'text': '有力', 'id': 'powerful'}

In [7]:
print(df['BENEFICIARY_info'].iloc[1])

{'markus_id': '24892a0a-56fd-4fa9-a133-bc6ca842414f', 'text': '行者', 'id': 'traveler'}

In [8]:
print(df['EVENT_info'].iloc[1])

{'markus_id': '8c8ff842-502a-4130-92bb-8d7274876358', 'text': '造', 'id': 'construct', 'type': 'RENOVATION'}

In [9]:
print(df['MATERIAL_info'].iloc[10])

{'markus_id': 'f1afe2f7-c11a-470b-a304-ec34b1f07f0f', 'text': '板', 'id': 'plank'}

In [10]:
print(df['OBJECT_MAIN_info'].iloc[10])

{'markus_id': '2bd68e56-44a2-49d7-867b-26f63478f1a5', 'text': '魏司馬西橋', 'id': 'pucheng_weisimaxi_qiao', 'type': 'bridge'}

In [11]:
print(df['LOCATION_info'].iloc[10])

{'markus_id': '17971000-a36e-4ac5-846b-fd36f92ec361', 'text': '浦城', 'id': 'hvd_40248'}

In [12]:
df['EVENT_info'].str.contains("};{", na=False).sum()

0

### 2a. Append the info inside the dictionary as separate columns for categories with unnested dictionary

In [80]:
# Define a function to extract 'text' and 'id' values from a dictionary
def extract_col_info(col_info):
    try:
        event_dict = ast.literal_eval(col_info)
        return (event_dict.get('text', None), event_dict.get('id', None))
    except (ValueError, SyntaxError):
        return (None, None)

In [81]:
df[['EVENT_text', 'EVENT_id']] = df['EVENT_info'].apply(lambda x: pd.Series(extract_col_info(x)))
df[['OBJECT_MAIN_text', 'OBJECT_MAIN_id']] = df['OBJECT_MAIN_info'].apply(lambda x: pd.Series(extract_col_info(x)))
df[['LOCATION_text', 'LOCATION_id']] = df['LOCATION_info'].apply(lambda x: pd.Series(extract_col_info(x)))

In [82]:
def extract_type_info(col_info):
    try:
        event_dict = ast.literal_eval(col_info)
        return (event_dict.get('type', None))
    except (ValueError, SyntaxError):
        return (None, None)

In [83]:
df[['EVENT_type']] = df['EVENT_info'].apply(lambda x: pd.Series(extract_type_info(x)))
df[['OBJECT_MAIN_type']] = df['OBJECT_MAIN_info'].apply(lambda x: pd.Series(extract_type_info(x)))

C:\Users\dawn\AppData\Local\Temp\ipykernel_16256\2086132294.py:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  df[['EVENT_type']] = df['EVENT_info'].apply(lambda x: pd.Series(extract_type_info(x)))
C:\Users\dawn\AppData\Local\Temp\ipykernel_16256\2086132294.py:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  df[['OBJECT_MAIN_type']] = df['OBJECT_MAIN_info'].apply(lambda x: pd.Series(extract_type_info(x)))

In [84]:
# Store the appended columns in a new dataframe
df_event = df
df_event

,Record_ID,Original_ID,File_Name,TIME_BEGIN_text,TIME_BEGIN_id,TIME_END_text,TIME_END_id,TIME_DURATION_text,TIME_DURATION_id,INITIATOR_info,...,TIME_AFTER_text,TIME_AFTER_id,EVENT_text,EVENT_id,OBJECT_MAIN_text,OBJECT_MAIN_id,LOCATION_text,LOCATION_id,EVENT_type,OBJECT_MAIN_type
0,record001,c67862cf-a766-4c45-89eb-ce4c3d71b8e1,Daoguang_ZhangpingXianzhi_Juanshou_Bubian_Wang...,九年三月,1829-04,復月望日,1829-05-17,不數月,x1月,{'markus_id': 'ccd1b930-e47b-498f-a2be-c6ae4f5...,...,NaN,NaN,更新,rebuild,文昌橋,zhangping_wenchang_qiao,漳平,hvd_40325,RENOVATION,bridge
1,record002,722e1ac9-4a50-4532-9551-0f2ecef1bb76,Guangxu_PingnanXianzhi_Juanzhishi_Yiwen_HuangX...,NaN,NaN,甲辰,1904,不數月,x1月,{'markus_id': '5af1576b-dda1-46a6-9556-8963e54...,...,NaN,NaN,造,construct,勸農,pingnan_quannong_qiao,屏南,hvd_40208,RENOVATION,bridge
2,record003,9eaccae1-9f20-46c7-8c82-48e835b21724,Guangxu_PingnanXianzhi_Juanzhishi_Yiwen_ZhouDa...,NaN,NaN,嘉慶十四年,1809,NaN,NaN,,...,NaN,NaN,蕩,wash_away,千乘,pingnan_qiancheng_qiao,屏南,hvd_40208,DESTRUCTION,bridge
3,record004,c3d348c4-2be6-4f64-9380-99f437f9681f,Guangxu_PingnanXianzhi_Juanzhishi_Yiwen_ZhouDa...,NaN,NaN,嘉慶二十五年,1820,NaN,NaN,{'markus_id': '357475b9-d32d-49c4-8337-60dfe31...,...,NaN,NaN,再造,reconstruct,千乘橋,pingnan_qiancheng_qiao,屏南,hvd_40208,RENOVATION,bridge
4,record005,e808dcda-4cdf-49e7-9487-9436ace47d56,Guangxu_PuchengXianzhi_Juanzhisanshiliu_Yiwens...,NaN,NaN,嘉靖六年,1527,NaN,NaN,{'markus_id': 'efbd2cf3-32a3-4631-bcf2-32dc2f5...,...,NaN,NaN,建,construct,魏司馬西橋,pucheng_weisimaxi_qiao,浦城,hvd_40248,RENOVATION,bridge
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426,record427,39ab932f-2ade-4538-9f02-7b2d69440858,Wanli_ZhengheXianzhi_Juanzhiba_Cihanzhi_YinZhi...,NaN,NaN,成化甲辰夏,1484,NaN,NaN,NaN,...,NaN,NaN,漂蕩,wash_away,星溪橋,zhenghe_xingxi_qiao,政和,hvd_40253,DESTRUCTION,bridge
427,record428,ed918c3e-acce-472e-a4a5-d2313bf02a18,Wanli_ZhengheXianzhi_Juanzhiba_Cihanzhi_YinZhi...,明年秋,1485,NaN,NaN,半載,6月,{'markus_id': '2d3f9ca1-4b13-4f64-bdca-88a8cce...,...,NaN,NaN,葺,repair,星溪橋,zhenghe_xingxi_qiao,政和,hvd_40253,RENOVATION,bridge
428,record429,507ce767-3298-454d-b348-729bf4a189de,Wanli_ZhengheXianzhi_Juanzhiba_Cihanzhi_ZouXix...,NaN,NaN,嘉靖乙卯,1555,NaN,NaN,{'markus_id': '72a3f009-8c83-437d-98ce-8529c45...,...,NaN,NaN,建,construct,熈寧,zhenghe_xining_qiao,政和,hvd_40253,CONSTRUCTION,bridge
429,record430,c339a5f3-fc75-46dd-bfb9-481a85342d5b,Wanli_ZhengheXianzhi_Juanzhiba_Cihanzhi_ZouXix...,NaN,NaN,萬曆乙未,1595,NaN,NaN,,...,NaN,NaN,燬,burn,熈寧,zhenghe_xining_qiao,政和,hvd_40253,DESTRUCTION,bridge
430,record431,4137ccca-3d31-47ad-bed5-4da54cac67c6,Wanli_ZhengheXianzhi_Juanzhiba_Cihanzhi_ZouXix...,NaN,NaN,丁酉,1597,幾閱月,x1月,{'markus_id': 'a96f055a-4356-4eb8-91de-b5cf62e...,...,NaN,NaN,興,raise,熈寧,zhenghe_xining_qiao,政和,hvd_40253,RENOVATION,bridge

In [19]:
print(df_event.columns)

Index(['Record_ID', 'Original_ID', 'File_Name', 'TIME_BEGIN_text',
       'TIME_BEGIN_id', 'TIME_END_text', 'TIME_END_id', 'TIME_DURATION_text',
       'TIME_DURATION_id', 'INITIATOR_info', 'EVENT_info', 'MATERIAL_info',
       'LOCATION_info', 'OBJECT_MAIN_info', 'EVENT_CAUSE_info', 'SPONSOR_info',
       'COST_info', 'FUNDING_ORIGIN_info', 'OBJECT_MEANING_info',
       'OBJ_PART_LINKED_info', 'id', 'LABOR_ORIGIN_info', 'OBJECT_LENGTH_info',
       'BENEFICIARY_info', 'OBJECT_ALT_NAME_info', 'OBJECT_DEITY_info',
       'OBJECT_WIDTH_info', 'OBJECT_HEIGHT_info', 'LABOR_info',
       'TIME_None_text', 'TIME_None_id', 'PLACE_LINKED_info',
       'TIME_BEFORE_text', 'TIME_BEFORE_id', 'TIME_AFTER_text',
       'TIME_AFTER_id', 'EVENT_text', 'EVENT_id', 'OBJECT_MAIN_text',
       'OBJECT_MAIN_id', 'LOCATION_text', 'LOCATION_id', 'EVENT_type',
       'OBJECT_MAIN_type'],
      dtype='object')

### 2b. Explode the info in the nested dictionary as separate rows for the categories that I want to observe

In [85]:
df_event['INITIATOR_info'] = df_event['INITIATOR_info'].str.split(';')
df_event = df_event.explode('INITIATOR_info')
df_event[['INITIATOR_text', 'INITIATOR_id']] = df_event['INITIATOR_info'].apply(lambda x: pd.Series(extract_col_info(x)))

df_event['SPONSOR_info'] = df_event['SPONSOR_info'].str.split(';')
df_event = df_event.explode('SPONSOR_info')
df_event[['SPONSOR_text', 'SPONSOR_id']] = df_event['SPONSOR_info'].apply(lambda x: pd.Series(extract_col_info(x)))

df_event['BENEFICIARY_info'] = df_event['BENEFICIARY_info'].str.split(';')
df_event = df_event.explode('BENEFICIARY_info')
df_event[['BENEFICIARY_text', 'BENEFICIARY_id']] = df_event['BENEFICIARY_info'].apply(lambda x: pd.Series(extract_col_info(x)))

df_event['MATERIAL_info'] = df_event['MATERIAL_info'].str.split(';')
df_event = df_event.explode('MATERIAL_info')
df_event[['MATERIAL_text', 'MATERIAL_id']] = df_event['MATERIAL_info'].apply(lambda x: pd.Series(extract_col_info(x)))

In [27]:
df_event

,Record_ID,Original_ID,File_Name,TIME_BEGIN_text,TIME_BEGIN_id,TIME_END_text,TIME_END_id,TIME_DURATION_text,TIME_DURATION_id,INITIATOR_info,...,EVENT_type,OBJECT_MAIN_type,INITIATOR_text,INITIATOR_id,SPONSOR_text,SPONSOR_id,BENEFICIARY_text,BENEFICIARY_id,MATERIAL_text,MATERIAL_id
0,record001,c67862cf-a766-4c45-89eb-ce4c3d71b8e1,Daoguang_ZhangpingXianzhi_Juanshou_Bubian_Wang...,九年三月,1829-04,復月望日,1829-05-17,不數月,x1月,{'markus_id': 'ccd1b930-e47b-498f-a2be-c6ae4f5...,...,RENOVATION,bridge,侯,marquis,紳士,gentry,None,None,鏈,chain
0,record001,c67862cf-a766-4c45-89eb-ce4c3d71b8e1,Daoguang_ZhangpingXianzhi_Juanshou_Bubian_Wang...,九年三月,1829-04,復月望日,1829-05-17,不數月,x1月,{'markus_id': 'ccd1b930-e47b-498f-a2be-c6ae4f5...,...,RENOVATION,bridge,侯,marquis,紳士,gentry,None,None,雙板,double_plank
0,record001,c67862cf-a766-4c45-89eb-ce4c3d71b8e1,Daoguang_ZhangpingXianzhi_Juanshou_Bubian_Wang...,九年三月,1829-04,復月望日,1829-05-17,不數月,x1月,{'markus_id': 'a1e983c3-5b80-4c86-b184-bf63235...,...,RENOVATION,bridge,盧侯,盧紳|fl1828|o漳平,紳士,gentry,None,None,鏈,chain
0,record001,c67862cf-a766-4c45-89eb-ce4c3d71b8e1,Daoguang_ZhangpingXianzhi_Juanshou_Bubian_Wang...,九年三月,1829-04,復月望日,1829-05-17,不數月,x1月,{'markus_id': 'a1e983c3-5b80-4c86-b184-bf63235...,...,RENOVATION,bridge,盧侯,盧紳|fl1828|o漳平,紳士,gentry,None,None,雙板,double_plank
1,record002,722e1ac9-4a50-4532-9551-0f2ecef1bb76,Guangxu_PingnanXianzhi_Juanzhishi_Yiwen_HuangX...,NaN,NaN,甲辰,1904,不數月,x1月,{'markus_id': '5af1576b-dda1-46a6-9556-8963e54...,...,RENOVATION,bridge,住持,abbot,有財者,wealthy,行者,traveler,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,record431,4137ccca-3d31-47ad-bed5-4da54cac67c6,Wanli_ZhengheXianzhi_Juanzhiba_Cihanzhi_ZouXix...,NaN,NaN,丁酉,1597,幾閱月,x1月,{'markus_id': '0b05b524-3454-41c6-957b-f913ee0...,...,RENOVATION,bridge,車公,車鳴時|fl1597|r歸善,劉君一璉,劉一璉|fl1595|o政和,耕,peasant,石,stone
430,record431,4137ccca-3d31-47ad-bed5-4da54cac67c6,Wanli_ZhengheXianzhi_Juanzhiba_Cihanzhi_ZouXix...,NaN,NaN,丁酉,1597,幾閱月,x1月,{'markus_id': '0b05b524-3454-41c6-957b-f913ee0...,...,RENOVATION,bridge,車公,車鳴時|fl1597|r歸善,劉君一璉,劉一璉|fl1595|o政和,牧者,herdsman,甃,brick
430,record431,4137ccca-3d31-47ad-bed5-4da54cac67c6,Wanli_ZhengheXianzhi_Juanzhiba_Cihanzhi_ZouXix...,NaN,NaN,丁酉,1597,幾閱月,x1月,{'markus_id': '0b05b524-3454-41c6-957b-f913ee0...,...,RENOVATION,bridge,車公,車鳴時|fl1597|r歸善,劉君一璉,劉一璉|fl1595|o政和,牧者,herdsman,石,stone
430,record431,4137ccca-3d31-47ad-bed5-4da54cac67c6,Wanli_ZhengheXianzhi_Juanzhiba_Cihanzhi_ZouXix...,NaN,NaN,丁酉,1597,幾閱月,x1月,{'markus_id': '0b05b524-3454-41c6-957b-f913ee0...,...,RENOVATION,bridge,車公,車鳴時|fl1597|r歸善,劉君一璉,劉一璉|fl1595|o政和,嬉逰而盤桓者,tourist,甃,brick
430,record431,4137ccca-3d31-47ad-bed5-4da54cac67c6,Wanli_ZhengheXianzhi_Juanzhiba_Cihanzhi_ZouXix...,NaN,NaN,丁酉,1597,幾閱月,x1月,{'markus_id': '0b05b524-3454-41c6-957b-f913ee0...,...,RENOVATION,bridge,車公,車鳴時|fl1597|r歸善,劉君一璉,劉一璉|fl1595|o政和,嬉逰而盤桓者,tourist,石,stone

### 2c. Move the newly appended columns to the front and store the selected columns into .csv

In [86]:
# Extract the newly appended columns
columns_to_move = df_event.iloc[:, -16:]
df_event.drop(df_event.columns[-16:], axis=1, inplace=True)

In [87]:
# Iterate over the columns in reversed order
for column in reversed(columns_to_move.columns):
    # Get the column values
    column_values = columns_to_move[column]
    
    # Insert the column at the desired position
    df_event.insert(3, column, column_values)

In [88]:
df_event.iloc[:,:25]

,Record_ID,Original_ID,File_Name,EVENT_text,EVENT_id,OBJECT_MAIN_text,OBJECT_MAIN_id,LOCATION_text,LOCATION_id,EVENT_type,...,BENEFICIARY_text,BENEFICIARY_id,MATERIAL_text,MATERIAL_id,TIME_BEGIN_text,TIME_BEGIN_id,TIME_END_text,TIME_END_id,TIME_DURATION_text,TIME_DURATION_id
0,record001,c67862cf-a766-4c45-89eb-ce4c3d71b8e1,Daoguang_ZhangpingXianzhi_Juanshou_Bubian_Wang...,更新,rebuild,文昌橋,zhangping_wenchang_qiao,漳平,hvd_40325,RENOVATION,...,None,None,鏈,chain,九年三月,1829-04,復月望日,1829-05-17,不數月,x1月
0,record001,c67862cf-a766-4c45-89eb-ce4c3d71b8e1,Daoguang_ZhangpingXianzhi_Juanshou_Bubian_Wang...,更新,rebuild,文昌橋,zhangping_wenchang_qiao,漳平,hvd_40325,RENOVATION,...,None,None,雙板,double_plank,九年三月,1829-04,復月望日,1829-05-17,不數月,x1月
0,record001,c67862cf-a766-4c45-89eb-ce4c3d71b8e1,Daoguang_ZhangpingXianzhi_Juanshou_Bubian_Wang...,更新,rebuild,文昌橋,zhangping_wenchang_qiao,漳平,hvd_40325,RENOVATION,...,None,None,鏈,chain,九年三月,1829-04,復月望日,1829-05-17,不數月,x1月
0,record001,c67862cf-a766-4c45-89eb-ce4c3d71b8e1,Daoguang_ZhangpingXianzhi_Juanshou_Bubian_Wang...,更新,rebuild,文昌橋,zhangping_wenchang_qiao,漳平,hvd_40325,RENOVATION,...,None,None,雙板,double_plank,九年三月,1829-04,復月望日,1829-05-17,不數月,x1月
1,record002,722e1ac9-4a50-4532-9551-0f2ecef1bb76,Guangxu_PingnanXianzhi_Juanzhishi_Yiwen_HuangX...,造,construct,勸農,pingnan_quannong_qiao,屏南,hvd_40208,RENOVATION,...,行者,traveler,None,None,NaN,NaN,甲辰,1904,不數月,x1月
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,record431,4137ccca-3d31-47ad-bed5-4da54cac67c6,Wanli_ZhengheXianzhi_Juanzhiba_Cihanzhi_ZouXix...,興,raise,熈寧,zhenghe_xining_qiao,政和,hvd_40253,RENOVATION,...,耕,peasant,石,stone,NaN,NaN,丁酉,1597,幾閱月,x1月
430,record431,4137ccca-3d31-47ad-bed5-4da54cac67c6,Wanli_ZhengheXianzhi_Juanzhiba_Cihanzhi_ZouXix...,興,raise,熈寧,zhenghe_xining_qiao,政和,hvd_40253,RENOVATION,...,牧者,herdsman,甃,brick,NaN,NaN,丁酉,1597,幾閱月,x1月
430,record431,4137ccca-3d31-47ad-bed5-4da54cac67c6,Wanli_ZhengheXianzhi_Juanzhiba_Cihanzhi_ZouXix...,興,raise,熈寧,zhenghe_xining_qiao,政和,hvd_40253,RENOVATION,...,牧者,herdsman,石,stone,NaN,NaN,丁酉,1597,幾閱月,x1月
430,record431,4137ccca-3d31-47ad-bed5-4da54cac67c6,Wanli_ZhengheXianzhi_Juanzhiba_Cihanzhi_ZouXix...,興,raise,熈寧,zhenghe_xining_qiao,政和,hvd_40253,RENOVATION,...,嬉逰而盤桓者,tourist,甃,brick,NaN,NaN,丁酉,1597,幾閱月,x1月
430,record431,4137ccca-3d31-47ad-bed5-4da54cac67c6,Wanli_ZhengheXianzhi_Juanzhiba_Cihanzhi_ZouXix...,興,raise,熈寧,zhenghe_xining_qiao,政和,hvd_40253,RENOVATION,...,嬉逰而盤桓者,tourist,石,stone,NaN,NaN,丁酉,1597,幾閱月,x1月

In [89]:
dfnew = df_event.iloc[:,:25]
dfnew

,Record_ID,Original_ID,File_Name,EVENT_text,EVENT_id,OBJECT_MAIN_text,OBJECT_MAIN_id,LOCATION_text,LOCATION_id,EVENT_type,...,BENEFICIARY_text,BENEFICIARY_id,MATERIAL_text,MATERIAL_id,TIME_BEGIN_text,TIME_BEGIN_id,TIME_END_text,TIME_END_id,TIME_DURATION_text,TIME_DURATION_id
0,record001,c67862cf-a766-4c45-89eb-ce4c3d71b8e1,Daoguang_ZhangpingXianzhi_Juanshou_Bubian_Wang...,更新,rebuild,文昌橋,zhangping_wenchang_qiao,漳平,hvd_40325,RENOVATION,...,None,None,鏈,chain,九年三月,1829-04,復月望日,1829-05-17,不數月,x1月
0,record001,c67862cf-a766-4c45-89eb-ce4c3d71b8e1,Daoguang_ZhangpingXianzhi_Juanshou_Bubian_Wang...,更新,rebuild,文昌橋,zhangping_wenchang_qiao,漳平,hvd_40325,RENOVATION,...,None,None,雙板,double_plank,九年三月,1829-04,復月望日,1829-05-17,不數月,x1月
0,record001,c67862cf-a766-4c45-89eb-ce4c3d71b8e1,Daoguang_ZhangpingXianzhi_Juanshou_Bubian_Wang...,更新,rebuild,文昌橋,zhangping_wenchang_qiao,漳平,hvd_40325,RENOVATION,...,None,None,鏈,chain,九年三月,1829-04,復月望日,1829-05-17,不數月,x1月
0,record001,c67862cf-a766-4c45-89eb-ce4c3d71b8e1,Daoguang_ZhangpingXianzhi_Juanshou_Bubian_Wang...,更新,rebuild,文昌橋,zhangping_wenchang_qiao,漳平,hvd_40325,RENOVATION,...,None,None,雙板,double_plank,九年三月,1829-04,復月望日,1829-05-17,不數月,x1月
1,record002,722e1ac9-4a50-4532-9551-0f2ecef1bb76,Guangxu_PingnanXianzhi_Juanzhishi_Yiwen_HuangX...,造,construct,勸農,pingnan_quannong_qiao,屏南,hvd_40208,RENOVATION,...,行者,traveler,None,None,NaN,NaN,甲辰,1904,不數月,x1月
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,record431,4137ccca-3d31-47ad-bed5-4da54cac67c6,Wanli_ZhengheXianzhi_Juanzhiba_Cihanzhi_ZouXix...,興,raise,熈寧,zhenghe_xining_qiao,政和,hvd_40253,RENOVATION,...,耕,peasant,石,stone,NaN,NaN,丁酉,1597,幾閱月,x1月
430,record431,4137ccca-3d31-47ad-bed5-4da54cac67c6,Wanli_ZhengheXianzhi_Juanzhiba_Cihanzhi_ZouXix...,興,raise,熈寧,zhenghe_xining_qiao,政和,hvd_40253,RENOVATION,...,牧者,herdsman,甃,brick,NaN,NaN,丁酉,1597,幾閱月,x1月
430,record431,4137ccca-3d31-47ad-bed5-4da54cac67c6,Wanli_ZhengheXianzhi_Juanzhiba_Cihanzhi_ZouXix...,興,raise,熈寧,zhenghe_xining_qiao,政和,hvd_40253,RENOVATION,...,牧者,herdsman,石,stone,NaN,NaN,丁酉,1597,幾閱月,x1月
430,record431,4137ccca-3d31-47ad-bed5-4da54cac67c6,Wanli_ZhengheXianzhi_Juanzhiba_Cihanzhi_ZouXix...,興,raise,熈寧,zhenghe_xining_qiao,政和,hvd_40253,RENOVATION,...,嬉逰而盤桓者,tourist,甃,brick,NaN,NaN,丁酉,1597,幾閱月,x1月
430,record431,4137ccca-3d31-47ad-bed5-4da54cac67c6,Wanli_ZhengheXianzhi_Juanzhiba_Cihanzhi_ZouXix...,興,raise,熈寧,zhenghe_xining_qiao,政和,hvd_40253,RENOVATION,...,嬉逰而盤桓者,tourist,石,stone,NaN,NaN,丁酉,1597,幾閱月,x1月

In [26]:
dfnew.to_csv('C:/Users/dawn/Desktop/SNA_try/Fujian_event_df.csv', encoding='utf-8', index=False)

### 3. Etract object lists for SNA

#### a. distinct event list

In [49]:
event_list = dfnew.groupby('Record_ID').agg({
    'EVENT_text': 'first', 
    'EVENT_id': 'first', 
    'EVENT_type': 'first', 
    'TIME_BEGIN_id': 'first', 
    'TIME_BEGIN_text': 'first',
    'TIME_END_text': 'first',
    'TIME_END_id': 'first', 
    'TIME_DURATION_id': 'first', 
    'TIME_DURATION_text': 'first'
}).reset_index()

event_list

,Record_ID,EVENT_text,EVENT_id,EVENT_type,TIME_BEGIN_id,TIME_BEGIN_text,TIME_END_text,TIME_END_id,TIME_DURATION_id,TIME_DURATION_text
0,record001,更新,rebuild,RENOVATION,1829-04,九年三月,復月望日,1829-05-17,x1月,不數月
1,record002,造,construct,RENOVATION,None,None,甲辰,1904,x1月,不數月
2,record003,蕩,wash_away,DESTRUCTION,None,None,嘉慶十四年,1809,None,None
3,record004,再造,reconstruct,RENOVATION,None,None,嘉慶二十五年,1820,None,None
4,record005,建,construct,RENOVATION,None,None,嘉靖六年,1527,None,None
...,...,...,...,...,...,...,...,...,...,...
426,record427,漂蕩,wash_away,DESTRUCTION,None,None,成化甲辰夏,1484,None,None
427,record428,葺,repair,RENOVATION,1485,明年秋,None,None,6月,半載
428,record429,建,construct,CONSTRUCTION,None,None,嘉靖乙卯,1555,None,None
429,record430,燬,burn,DESTRUCTION,None,None,萬曆乙未,1595,None,None
430,record431,興,raise,RENOVATION,None,None,丁酉,1597,x1月,幾閱月

#### b. distinct object_main list

In [37]:
object_list = dfnew.groupby('OBJECT_MAIN_id').agg({
    'OBJECT_MAIN_text': 'first', 
    'OBJECT_MAIN_type': 'first'
}).reset_index()

object_list

             OBJECT_MAIN_id OBJECT_MAIN_text OBJECT_MAIN_type
0    changtai_chaojing_qiao               朝京           bridge
1        changtai_hudu_qiao              虎渡橋           bridge
2    changting_taiping_qiao               太平           bridge
3        dehua_hualong_qiao              化龍橋           bridge
4          fu'an_xikou_qiao               溪口           bridge
..                      ...              ...              ...
97      zhao'an_dongxi_qiao             東溪石橋           bridge
98    zhao'an_guangnan_qiao               廣南           bridge
99     zhao'an_longwei_qiao              龍尾橋           bridge
100     zhenghe_xingxi_qiao              星溪橋           bridge
101     zhenghe_xining_qiao               熈寧           bridge

[102 rows x 3 columns]

#### c. distinct material list

In [74]:
material_list = dfnew.groupby('MATERIAL_id').agg({
    'MATERIAL_text': 'first'
}).reset_index()

material_list

     MATERIAL_id MATERIAL_text
0         bamboo             簰
1           boat             舟
2        boulder            磐石
3          brick            捲甃
4          chain             鏈
5   cinnabar_red            丹雘
6   double_plank            雙板
7          earth             土
8         gravel            碎石
9     huge_stone            巨石
10     huge_wood            巨木
11          iron             鐡
12   large_stone            巨石
13    large_wood            大木
14    long_plank            長板
15      material             木
16         metal             金
17          pine             松
18     pine_wood            松木
19         plank             板
20       pottery             陶
21         stone             石
22          tile             甎
23          wood             木
24    wood_plank            木板

#### d. distinct location list (parsed corresponding coordinates from TGAZ)

In [46]:
location_list = dfnew.groupby('LOCATION_id').agg({
    'LOCATION_text': 'first'
}).reset_index()

location_list

   LOCATION_id LOCATION_text
0   hvd_196439            光澤
1    hvd_32123             汀
2    hvd_32131            延平
3    hvd_40198            福清
4    hvd_40201            福安
5    hvd_40207            古田
6    hvd_40208            屏南
7    hvd_40212             永
8    hvd_40228             建
9    hvd_40234             甌
10   hvd_40241            建陽
11   hvd_40248            浦城
12   hvd_40251             松
13   hvd_40253            政和
14   hvd_40257            晉江
15   hvd_40258            惠安
16   hvd_40260            同安
17   hvd_40273            光澤
18   hvd_40277            建寧
19   hvd_40282             汀
20   hvd_40287            清流
21   hvd_40294             杭
22   hvd_40296            永定
23   hvd_40300            僊遊
24   hvd_40309            順昌
25   hvd_40313            將樂
26   hvd_40322            德化
27   hvd_40325            漳平
28   hvd_40326            甯洋
29   hvd_40328            龍溪
30   hvd_40332            海澄
31   hvd_40339            長泰
32   hvd_40342            詔安
33          杉溪            杉溪

In [51]:
import requests
from bs4 import BeautifulSoup

# Initialize lists to store uri and coordinates
uris = []
coordinates_list = []

# Function to extract coordinates from URI
def extract_coordinates(uri):
    response = requests.get(uri)
    if response.status_code == 200:
        soup = BeautifulSoup(response.content, 'html.parser')
        degrees_latitude = soup.find('degrees-latitude').text.strip()
        degrees_longitude = soup.find('degrees-longitude').text.strip()
        latitude_direction = soup.find('latitude-direction').text.strip()
        longitude_direction = soup.find('longitude-direction').text.strip()
        coordinates = f"{degrees_latitude} {latitude_direction}, {degrees_longitude} {longitude_direction}"
        return coordinates
    else:
        return None

# Iterate through rows of the DataFrame
for index, row in location_list.iterrows():
    uri = f"https://maps.cga.harvard.edu/tgaz/placename/{row['LOCATION_id']}"
    uris.append(uri)
    coordinates = extract_coordinates(uri)
    coordinates_list.append(coordinates)

# Add 'uri' and 'coordinates' columns to the DataFrame
location_list['LOCATION_uri'] = uris
location_list['LOCATION_coordinates'] = coordinates_list

location_list

,LOCATION_id,LOCATION_text,LOCATION_uri,LOCATION_coordinates
0,hvd_196439,光澤,https://maps.cga.harvard.edu/tgaz/placename/hv...,"0.00000 N, 0.00000 E"
1,hvd_32123,汀,https://maps.cga.harvard.edu/tgaz/placename/hv...,"25.83338 N, 116.34954 E"
2,hvd_32131,延平,https://maps.cga.harvard.edu/tgaz/placename/hv...,"26.64217 N, 118.16918 E"
3,hvd_40198,福清,https://maps.cga.harvard.edu/tgaz/placename/hv...,"25.72792 N, 119.38144 E"
4,hvd_40201,福安,https://maps.cga.harvard.edu/tgaz/placename/hv...,"27.08866 N, 119.64677 E"
5,hvd_40207,古田,https://maps.cga.harvard.edu/tgaz/placename/hv...,"26.60171 N, 118.78490 E"
6,hvd_40208,屏南,https://maps.cga.harvard.edu/tgaz/placename/hv...,"27.02546 N, 119.03923 E"
7,hvd_40212,永,https://maps.cga.harvard.edu/tgaz/placename/hv...,"25.86762 N, 118.93410 E"
8,hvd_40228,建,https://maps.cga.harvard.edu/tgaz/placename/hv...,"27.03886 N, 118.32378 E"
9,hvd_40234,甌,https://maps.cga.harvard.edu/tgaz/placename/hv...,"27.03886 N, 118.32378 E"
10,hvd_40241,建陽,https://maps.cga.harvard.edu/tgaz/placename/hv...,"27.33988 N, 118.10537 E"
11,hvd_40248,浦城,https://maps.cga.harvard.edu/tgaz/placename/hv...,"27.92469 N, 118.53625 E"
12,hvd_40251,松,https://maps.cga.harvard.edu/tgaz/placename/hv...,"27.52840 N, 118.77461 E"
13,hvd_40253,政和,https://maps.cga.harvard.edu/tgaz/placename/hv...,"27.37210 N, 118.85319 E"
14,hvd_40257,晉江,https://maps.cga.harvard.edu/tgaz/placename/hv...,"24.90964 N, 118.58990 E"
15,hvd_40258,惠安,https://maps.cga.harvard.edu/tgaz/placename/hv...,"25.02208 N, 118.80282 E"
16,hvd_40260,同安,https://maps.cga.harvard.edu/tgaz/placename/hv...,"24.73605 N, 118.14412 E"
17,hvd_40273,光澤,https://maps.cga.harvard.edu/tgaz/placename/hv...,"27.53952 N, 117.33325 E"
18,hvd_40277,建寧,https://maps.cga.harvard.edu/tgaz/placename/hv...,"26.83249 N, 116.83253 E"
19,hvd_40282,汀,https://maps.cga.harvard.edu/tgaz/placename/hv...,"25.83338 N, 116.34954 E"
20,hvd_40287,清流,https://maps.cga.harvard.edu/tgaz/placename/hv...,"26.16352 N, 116.81414 E"
21,hvd_40294,杭,https://maps.cga.harvard.edu/tgaz/placename/hv...,"25.05334 N, 116.41784 E"
22,hvd_40296,永定,https://maps.cga.harvard.edu/tgaz/placename/hv...,"24.72038 N, 116.72076 E"
23,hvd_40300,僊遊,https://maps.cga.harvard.edu/tgaz/placename/hv...,"25.36456 N, 118.68367 E"
24,hvd_40309,順昌,https://maps.cga.harvard.edu/tgaz/placename/hv...,"26.79709 N, 117.80628 E"
25,hvd_40313,將樂,https://maps.cga.harvard.edu/tgaz/placename/hv...,"26.72082 N, 117.45502 E"
26,hvd_40322,德化,https://maps.cga.harvard.edu/tgaz/placename/hv...,"25.47695 N, 118.22922 E"
27,hvd_40325,漳平,https://maps.cga.harvard.edu/tgaz/placename/hv...,"25.28946 N, 117.40403 E"
28,hvd_40326,甯洋,https://maps.cga.harvard.edu/tgaz/placename/hv...,"25.61503 N, 117.36434 E"
29,hvd_40328,龍溪,https://maps.cga.harvard.edu/tgaz/placename/hv...,"24.51174 N, 117.65305 E"
30,hvd_40332,海澄,https://maps.cga.harvard.edu/tgaz/placename/hv...,"24.41141 N, 117.85114 E"
31,hvd_40339,長泰,https://maps.cga.harvard.edu/tgaz/placename/hv...,"24.62048 N, 117.75055 E"
32,hvd_40342,詔安,https://maps.cga.harvard.edu/tgaz/placename/hv...,"23.70535 N, 117.17490 E"
33,杉溪,杉溪,https://maps.cga.harvard.edu/tgaz/placename/杉溪,None

#### e. distinct actor list (concat sponsor, initiator and beneficiary)

In [47]:
# Concatenate SPONSOR, INITIATOR, and BENEFICIARY columns into a single column ACTOR
actor_list = pd.concat([
    dfnew[['SPONSOR_id', 'SPONSOR_text']].rename(columns={'SPONSOR_id': 'ACTOR_id', 'SPONSOR_text': 'ACTOR_text'}),
    dfnew[['INITIATOR_id', 'INITIATOR_text']].rename(columns={'INITIATOR_id': 'ACTOR_id', 'INITIATOR_text': 'ACTOR_text'}),
    dfnew[['BENEFICIARY_id', 'BENEFICIARY_text']].rename(columns={'BENEFICIARY_id': 'ACTOR_id', 'BENEFICIARY_text': 'ACTOR_text'})
])

# Group by ACTOR_id and aggregate ACTOR_text
actor_list = actor_list.groupby('ACTOR_id')['ACTOR_text'].unique().apply(lambda x: ', '.join(x)).reset_index()
actor_list

           ACTOR_id ACTOR_text
0            103279        李良杰
1            112212        賴德翰
2            116072     也只里海牙公
3             12053          遂
4            124844       趙君象賢
..              ...        ...
844  龔元選|fl1594|r光澤        龔元選
845  龔宏文|fl1736|r光澤  龔君宏文, 龔宏文
846  龔日文|fl1424|r光澤        龔日文
847  龔清波|fl1736|r光澤        龔清波
848  龔華通|fl1517|r光澤        龔華通

[849 rows x 2 columns]

In [75]:
event_list.to_csv('C:/Users/dawn/Desktop/SNA_try/Fujian_eventlist.csv', encoding='utf-8', index=False)
location_list.to_csv('C:/Users/dawn/Desktop/SNA_try/Fujian_locationlist.csv', encoding='utf-8', index=False)
object_list.to_csv('C:/Users/dawn/Desktop/SNA_try/Fujian_objectlist.csv', encoding='utf-8', index=False)
actor_list.to_csv('C:/Users/dawn/Desktop/SNA_try/Fujian_actorlist.csv', encoding='utf-8', index=False)
material_list.to_csv('C:/Users/dawn/Desktop/SNA_try/Fujian_materiallist.csv', encoding='utf-8', index=False)

### tryout: store the concated info in single row with seperator

In [62]:
# Define a dictionary to store the column names and their corresponding concatenated column names
columns_to_concat = {
    'INITIATOR_id': 'INITIATOR_concatenated',
    'SPONSOR_id': 'SPONSOR_concatenated',
    'BENEFICIARY_id': 'BENEFICIARY_concatenated',
    'MATERIAL_id': 'MATERIAL_concatenated'
}

# Group by 'Record_ID' and concatenate values for each specified column
df_grouped = pd.DataFrame()
for column, concat_column in columns_to_concat.items():
    grouped = dfnew.groupby('Record_ID')[column].agg(lambda x: ';'.join(str(i) for i in x if i is not None)).reset_index()
    grouped.rename(columns={column: concat_column}, inplace=True)
    if df_grouped.empty:
        df_grouped = grouped
    else:
        df_grouped = pd.merge(df_grouped, grouped, on='Record_ID', how='outer')

# Remove duplicates from concatenated columns
for column in columns_to_concat.values():
    df_grouped[column] = df_grouped[column].apply(lambda x: ';'.join(pd.unique(x.split(';'))))

df_grouped

,Record_ID,INITIATOR_concatenated,SPONSOR_concatenated,BENEFICIARY_concatenated,MATERIAL_concatenated
0,record001,marquis;盧紳|fl1828|o漳平,gentry,,chain;double_plank
1,record002,abbot;地慧|fl1904|r屏南,wealthy;powerful,traveler,
2,record003,,,,
3,record004,colleague,,minister;rider;traveler;peasant;scholar;merchant,
4,record005,謝元賜|fl1527|r浦城?,,,
...,...,...,...,...,...
426,record427,,,,
427,record428,magistrate;柴曦|fl1485|r建德,vice_magistrate;assistant_magistrate;assistant...,,wood;stone
428,record429,people;陳脩|fl1555|r政和,,,wood
429,record430,,,,
430,record431,magistrate;車鳴時|fl1597|r歸善,gentry;吳道敷|fl1595|r政和;張希榮|fl1595|r政和;gentlemen...,traveler;porter;firewood_collector;peasant;her...,brick;stone

In [76]:
df_grouped.to_csv('C:/Users/dawn/Desktop/SNA_try/Fujian_multiplecon.csv', encoding='utf-8', index=False)

In [72]:
merged_df = pd.merge(df_event, df_grouped, on='Record_ID', how='left')
merged_df

,Record_ID,Original_ID,File_Name,TIME_BEGIN_text,TIME_BEGIN_id,TIME_END_text,TIME_END_id,TIME_DURATION_text,TIME_DURATION_id,INITIATOR_info,...,OBJECT_MAIN_text,OBJECT_MAIN_id,LOCATION_text,LOCATION_id,EVENT_type,OBJECT_MAIN_type,INITIATOR_concatenated,SPONSOR_concatenated,BENEFICIARY_concatenated,MATERIAL_concatenated
0,record001,c67862cf-a766-4c45-89eb-ce4c3d71b8e1,Daoguang_ZhangpingXianzhi_Juanshou_Bubian_Wang...,九年三月,1829-04,復月望日,1829-05-17,不數月,x1月,{'markus_id': 'ccd1b930-e47b-498f-a2be-c6ae4f5...,...,文昌橋,zhangping_wenchang_qiao,漳平,hvd_40325,RENOVATION,bridge,marquis;盧紳|fl1828|o漳平,gentry,,chain;double_plank
1,record002,722e1ac9-4a50-4532-9551-0f2ecef1bb76,Guangxu_PingnanXianzhi_Juanzhishi_Yiwen_HuangX...,NaN,NaN,甲辰,1904,不數月,x1月,{'markus_id': '5af1576b-dda1-46a6-9556-8963e54...,...,勸農,pingnan_quannong_qiao,屏南,hvd_40208,RENOVATION,bridge,abbot;地慧|fl1904|r屏南,wealthy;powerful,traveler,
2,record003,9eaccae1-9f20-46c7-8c82-48e835b21724,Guangxu_PingnanXianzhi_Juanzhishi_Yiwen_ZhouDa...,NaN,NaN,嘉慶十四年,1809,NaN,NaN,,...,千乘,pingnan_qiancheng_qiao,屏南,hvd_40208,DESTRUCTION,bridge,,,,
3,record004,c3d348c4-2be6-4f64-9380-99f437f9681f,Guangxu_PingnanXianzhi_Juanzhishi_Yiwen_ZhouDa...,NaN,NaN,嘉慶二十五年,1820,NaN,NaN,{'markus_id': '357475b9-d32d-49c4-8337-60dfe31...,...,千乘橋,pingnan_qiancheng_qiao,屏南,hvd_40208,RENOVATION,bridge,colleague,,minister;rider;traveler;peasant;scholar;merchant,
4,record005,e808dcda-4cdf-49e7-9487-9436ace47d56,Guangxu_PuchengXianzhi_Juanzhisanshiliu_Yiwens...,NaN,NaN,嘉靖六年,1527,NaN,NaN,{'markus_id': 'efbd2cf3-32a3-4631-bcf2-32dc2f5...,...,魏司馬西橋,pucheng_weisimaxi_qiao,浦城,hvd_40248,RENOVATION,bridge,謝元賜|fl1527|r浦城?,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426,record427,39ab932f-2ade-4538-9f02-7b2d69440858,Wanli_ZhengheXianzhi_Juanzhiba_Cihanzhi_YinZhi...,NaN,NaN,成化甲辰夏,1484,NaN,NaN,NaN,...,星溪橋,zhenghe_xingxi_qiao,政和,hvd_40253,DESTRUCTION,bridge,,,,
427,record428,ed918c3e-acce-472e-a4a5-d2313bf02a18,Wanli_ZhengheXianzhi_Juanzhiba_Cihanzhi_YinZhi...,明年秋,1485,NaN,NaN,半載,6月,{'markus_id': '2d3f9ca1-4b13-4f64-bdca-88a8cce...,...,星溪橋,zhenghe_xingxi_qiao,政和,hvd_40253,RENOVATION,bridge,magistrate;柴曦|fl1485|r建德,vice_magistrate;assistant_magistrate;assistant...,,wood;stone
428,record429,507ce767-3298-454d-b348-729bf4a189de,Wanli_ZhengheXianzhi_Juanzhiba_Cihanzhi_ZouXix...,NaN,NaN,嘉靖乙卯,1555,NaN,NaN,{'markus_id': '72a3f009-8c83-437d-98ce-8529c45...,...,熈寧,zhenghe_xining_qiao,政和,hvd_40253,CONSTRUCTION,bridge,people;陳脩|fl1555|r政和,,,wood
429,record430,c339a5f3-fc75-46dd-bfb9-481a85342d5b,Wanli_ZhengheXianzhi_Juanzhiba_Cihanzhi_ZouXix...,NaN,NaN,萬曆乙未,1595,NaN,NaN,,...,熈寧,zhenghe_xining_qiao,政和,hvd_40253,DESTRUCTION,bridge,,,,
430,record431,4137ccca-3d31-47ad-bed5-4da54cac67c6,Wanli_ZhengheXianzhi_Juanzhiba_Cihanzhi_ZouXix...,NaN,NaN,丁酉,1597,幾閱月,x1月,{'markus_id': 'a96f055a-4356-4eb8-91de-b5cf62e...,...,熈寧,zhenghe_xining_qiao,政和,hvd_40253,RENOVATION,bridge,magistrate;車鳴時|fl1597|r歸善,gentry;吳道敷|fl1595|r政和;張希榮|fl1595|r政和;gentlemen...,traveler;porter;firewood_collector;peasant;her...,brick;stone

In [73]:
merged_df.to_csv('C:/Users/dawn/Desktop/SNA_try/Fujian_eventconcact.csv', encoding='utf-8', index=False)